import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Page Turner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <StoreProvider>{children}</StoreProvider>;
}

// <Toaster position="top-center" />
